### ISSUE TITLE
convert to p5.js

### ISSUE THREAD

**Issue by shiffman** [shiffman/Mom_sketch#3]

**Comment by shiffman** [comment]
completed with 8b4c1ebbd00ac3e4dafc223f3c44b28c1aaa1884.  This was a *exact* port of original code (with the array update).  The sketch can now be seen at:

http://shiffman.github.io/Mom_sketch/

**Comment by rachelzucker** [comment]
"Mom" says that the screen is a "fixed size" (whenever I do not know the right words I used quotation marks to designate "civilian" speech) and is therefore "cutting off" the right edge on my screen. Is there any way to fix this? Also, Dan, do you see what I mean by lack of "progression"? Any thoughts on this?
